### ISSUE TITLE
Getting a lot of 404 errors in the html report

### ISSUE THREAD

**Issue by michaelpcote** [stryker-mutator/stryker-html-reporter#13]
I've run into an issue that is causing a lot of 404 errors that makes the html reports unusable. 

The issue occurs whenever the report is able to condense a path to something like:

parentDir/childDir 

This happens because there is only 1 child directory or because only 1 child directory has .js files. So, for instance, because we group our features together something like this: 

feature -
    - js (contains directives, services, controllers)
    - css
    - partials

It is basically formatting incorrectly every time. The issue is that the report on the upper level will show

feature/js - and when you click into that link it then shows the js directory and all the files completely unstyled. The index.html for that file then is trying to reference the bootstrap and stryker.js files 1 level up, like "../bootstrap" when it should actually be "../../bootstrap". 

I think a lot of people may run into a similar issue.

Thanks,
Mike

**Comment by j-truax** [comment]
+1 I'm running into this issue as well

**Comment by simondel** [comment]
Well take a look at thus,  thanks for reporting!

**Comment by j-truax** [comment]
Any update on this issue? Should it be reposted to [main Stryker issue list](https://github.com/stryker-mutator/stryker/issues)?

**Comment by nicojs** [comment]
Yeah, we migrated the stryker-html-reporter into the main stryker repository. I'm planning a complete rewrite of this reporter using the new [`onScoreResultCalculated`](https://github.com/stryker-mutator/stryker/blob/master/packages/stryker-api/src/report/Reporter.ts#L45) reporter callback and [typed-html](https://www.npmjs.com/package/typed-html). 

That should simplify the code a lot and i'll also look into fixing this issue.

**Comment by j-truax** [comment]
@nicojs Thanks for the update and help in addressing this issue. :+1: 

I've reposted this to the main stryker repo here: https://github.com/stryker-mutator/stryker/issues/335

**Comment by simondel** [comment]
@j-truax Thanks! I'll close this issue for now as we'll fix it in the stryker repo.
